package loginregistro.usuariosGUI;

import loginregistro.usuariosDAL.ConexionBD;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import loginregistro.usuariosBL.usuariosBL;

/**
 *
 * @author chris
 */
public class GestionarUsuarios extends javax.swing.JFrame {

    DefaultTableModel modelo;

    /**
     * Creates new form GestionarUsuarios
     */
    public GestionarUsuarios() {
        initComponents();

        //Array para los titulos de la tabla
        String[] titulos = {"Nombre", "Apellido", "Nombre_Usuario", "Teléfono", "Correo", "Contraseña"};
        modelo = new DefaultTableModel(null, titulos);

        tblUsuarios.setModel(modelo);
        this.mostrarDatos();
        this.limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtNombreGestion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellidoGestion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombreUsuarioGestion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefonoGestion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCorreoGestion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtContrasenaGestion = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        txtConfirmarContraGestion = new javax.swing.JPasswordField();
        btnCrear = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 700));

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsuarios.setPreferredSize(new java.awt.Dimension(800, 300));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre:");

        txtNombreGestion.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreGestion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombreGestion.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Apellido:");

        txtApellidoGestion.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidoGestion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtApellidoGestion.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre de Usuario:");

        txtNombreUsuarioGestion.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreUsuarioGestion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombreUsuarioGestion.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Teléfono:");

        txtTelefonoGestion.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefonoGestion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTelefonoGestion.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Correo:");

        txtCorreoGestion.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreoGestion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCorreoGestion.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Contraseña:");

        txtContrasenaGestion.setBackground(new java.awt.Color(255, 255, 255));
        txtContrasenaGestion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtContrasenaGestion.setForeground(new java.awt.Color(0, 0, 0));
        txtContrasenaGestion.setPreferredSize(new java.awt.Dimension(250, 40));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Confirmar contraseña:");

        txtConfirmarContraGestion.setBackground(new java.awt.Color(255, 255, 255));
        txtConfirmarContraGestion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtConfirmarContraGestion.setForeground(new java.awt.Color(0, 0, 0));
        txtConfirmarContraGestion.setPreferredSize(new java.awt.Dimension(250, 40));

        btnCrear.setBackground(new java.awt.Color(51, 153, 0));
        btnCrear.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(0, 0, 0));
        btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/agregar-usuario (1).png"))); // NOI18N
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(0, 102, 255));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(0, 0, 0));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/lapiz.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/basura.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(102, 102, 102));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Gestión de Usuarios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefonoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtNombreGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtApellidoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNombreUsuarioGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtConfirmarContraGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel7)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(8, 8, 8)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(txtCorreoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtContrasenaGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(74, 74, 74)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnCrear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(btnCancelar))
                                .addGap(120, 120, 120))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jLabel8)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNombreGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtCorreoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnCrear))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtApellidoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtContrasenaGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNombreUsuarioGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnEliminar)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtConfirmarContraGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTelefonoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(281, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        ConexionBD objConexion = new ConexionBD();

        usuariosBL oUsuario = new usuariosBL();
        // Comprobación de igualdad de contraseñas
        String contrasena = txtContrasenaGestion.getText();
        String confirmarContra = txtConfirmarContraGestion.getText();
        String mensaje = "";

        if (contrasena.equals(confirmarContra)) {
            oUsuario.setContrasena(contrasena);
            oUsuario = recuperarDatosGUI();
            mensaje = "Usuario creado exitosamente.";
            JOptionPane.showMessageDialog(this, mensaje, "Éxito", JOptionPane.INFORMATION_MESSAGE);

        } else {
            //Mensaje de error en caso de que las contraseñas no coincidan
            mensaje = "Las contraseñas no coinciden. Por favor, intenta de nuevo.";
            JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
        }

        String strSentenciaInsert = String.format("INSERT INTO `gestionusuarios`.`usuarios` (`Nombre`, `Apellido`, "
                + "                                `Nombre_Usuario`, `Telefono`, `Correo`, `Contrasena`) "
                + "                                 VALUES ('%s', '%s', '%s', '%s', '%s', '%s')", oUsuario.getNombre(), oUsuario.getApellido(),
                oUsuario.getNombreUsuario(), oUsuario.getTelefono(), oUsuario.getCorreo(), oUsuario.getContrasena());

        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);

        this.mostrarDatos();

        this.limpiar();

    }//GEN-LAST:event_btnCrearActionPerformed

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            //obtiene toda la informacion del registro selecionado
            JTable receptor = (JTable) evt.getSource();

            txtNombreGestion.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 0).toString());
            txtApellidoGestion.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 1).toString());
            txtNombreUsuarioGestion.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 2).toString());
            txtTelefonoGestion.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 3).toString());
            txtCorreoGestion.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 4).toString());
            txtContrasenaGestion.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 5).toString());
            btnCrear.setEnabled(false);
            btnEditar.setEnabled(true);
            btnEliminar.setEnabled(true);
            //txtConfirmarContraGestion.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 6).toString());
        }
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        //Nos conectamos a la base de datos
        ConexionBD objConexion = new ConexionBD();

        //Obtenemos toda la informacion de la interfaz grafica
        usuariosBL oUsuario = recuperarDatosGUI();

        //Hacemos la sentencia de borrado
        String strSentenciaInsert = String.format("DELETE FROM Usuarios WHERE Nombre = '%s'", oUsuario.getNombre());

        //Ejecutar la sentencia SQL
        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);

        //Mostramos la informacion
        this.mostrarDatos();

        this.limpiar();

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        //Nos conectamos a la base de datos
        ConexionBD objConexion = new ConexionBD();

        //este objeto representa un objeto de la base de datos        
        usuariosBL oUsuario = new usuariosBL();
        oUsuario = recuperarDatosGUI();
        // Comprobación de igualdad de contraseñas
        String contrasena = txtContrasenaGestion.getText();
        String confirmarContra = txtConfirmarContraGestion.getText();
        String mensaje = "";

        if (contrasena.equals(confirmarContra)) {
            oUsuario.setContrasena(contrasena);

            mensaje = "Usuario editado exitosamente.";
            JOptionPane.showMessageDialog(this, mensaje, "Éxito", JOptionPane.INFORMATION_MESSAGE);

        } else {
            //Mensaje de error en caso de que las contraseñas no coincidan
            mensaje = "Las contraseñas no coinciden. Por favor, intenta de nuevo.";
            JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
        }

        String strSentenciaInsert = String.format("UPDATE Usuarios SET Nombre = '%s',Apellido = '%s',Nombre_Usuario = '%s',"
                + "                               Telefono='%s', Correo = '%s',Contrasena = '%s' WHERE Nombre = '%s'",
                oUsuario.getNombre(), oUsuario.getApellido(), oUsuario.getNombreUsuario(),
                oUsuario.getTelefono(), oUsuario.getCorreo(), oUsuario.getContrasena(), oUsuario.getNombre());

        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);

        this.mostrarDatos();
        this.limpiar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    public usuariosBL recuperarDatosGUI() {
        //int ID = (txtIDGestion.getText().isEmpty()?0: Integer.parseInt(txtID.getText()));
        usuariosBL oUsuario = new usuariosBL();

        oUsuario.setNombre(txtNombreGestion.getText());
        oUsuario.setApellido(txtApellidoGestion.getText());
        oUsuario.setNombreUsuario(txtNombreUsuarioGestion.getText());
        oUsuario.setCorreo(txtCorreoGestion.getText());
        oUsuario.setTelefono(txtTelefonoGestion.getText());

        // Comprobación de igualdad de contraseñas
        String contrasena = txtContrasenaGestion.getText();
        String confirmarContra = txtConfirmarContraGestion.getText();

        if (contrasena.equals(confirmarContra)) {
            oUsuario.setContrasena(contrasena);
        }


        return oUsuario;
    }

    public void mostrarDatos() {

        ConexionBD objConexion = new ConexionBD();

        //para hacer que los registros sean actualizados despues de cualquier sentencia
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }

        try {
            ResultSet resultado = objConexion.consultarRegistros("Select * from Usuarios");
            while (resultado.next()) {
                System.out.println(resultado.getString("ID"));
                System.out.println(resultado.getString("Nombre"));
                System.out.println(resultado.getString("Apellido"));
                System.out.println(resultado.getString("Nombre_Usuario"));
                System.out.println(resultado.getString("Telefono"));
                System.out.println(resultado.getString("Correo"));
                System.out.println(resultado.getString("Contrasena"));

                Object[] oUsuarios = {resultado.getString("Nombre"), resultado.getString("Apellido"),
                    resultado.getString("Nombre_Usuario"), resultado.getString("Telefono"),
                    resultado.getString("Correo"), resultado.getString("Contrasena")};
                modelo.addRow(oUsuarios);

            }

        } catch (Exception e) {
            System.out.println(e);

        }

    }

    public void limpiar() {
        //para limpiar los textos colocados en los campos
        txtNombreGestion.setText("");
        txtApellidoGestion.setText("");
        txtNombreUsuarioGestion.setText("");
        txtTelefonoGestion.setText("");
        txtCorreoGestion.setText("");
        txtContrasenaGestion.setText("");
        txtConfirmarContraGestion.setText("");

        //activa Crear y desactiva editar y eliminar
        btnCrear.setEnabled(true);
        btnEditar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtApellidoGestion;
    private javax.swing.JPasswordField txtConfirmarContraGestion;
    private javax.swing.JPasswordField txtContrasenaGestion;
    private javax.swing.JTextField txtCorreoGestion;
    private javax.swing.JTextField txtNombreGestion;
    private javax.swing.JTextField txtNombreUsuarioGestion;
    private javax.swing.JTextField txtTelefonoGestion;
    // End of variables declaration//GEN-END:variables
}
