package loginregistro.usuariosGUI;

import com.sun.jdi.connect.spi.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import loginregistro.usuariosBL.usuariosBL;
import loginregistro.usuariosDAL.ConexionBD;

/**
 *
 * @author chris
 */
public class LoginUsuarios extends javax.swing.JFrame {

    String correo, contrasena;

    /**
     * Creates new form formUsuarios
     */
    public LoginUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        derecho = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        izquierdo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCorreoLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnInciarSesion = new javax.swing.JButton();
        btnCrearCuenta = new javax.swing.JButton();
        txtContrasenaLogin = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        derecho.setBackground(new java.awt.Color(255, 255, 255));
        derecho.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logo-t4 (2).jpg"))); // NOI18N

        javax.swing.GroupLayout derechoLayout = new javax.swing.GroupLayout(derecho);
        derecho.setLayout(derechoLayout);
        derechoLayout.setHorizontalGroup(
            derechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, derechoLayout.createSequentialGroup()
                .addGap(0, 41, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        derechoLayout.setVerticalGroup(
            derechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, derechoLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        jPanel1.add(derecho);
        derecho.setBounds(0, 0, 400, 500);

        izquierdo.setBackground(new java.awt.Color(255, 255, 255));
        izquierdo.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Bienvenido!");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Correo:");

        txtCorreoLogin.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreoLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCorreoLogin.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoLoginActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Contraseña:");

        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("¿No tienes una cuenta?");

        btnInciarSesion.setBackground(new java.awt.Color(0, 0, 0));
        btnInciarSesion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnInciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnInciarSesion.setText("Iniciar sesión");
        btnInciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInciarSesionActionPerformed(evt);
            }
        });

        btnCrearCuenta.setBackground(new java.awt.Color(255, 255, 255));
        btnCrearCuenta.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnCrearCuenta.setForeground(new java.awt.Color(0, 51, 204));
        btnCrearCuenta.setText("Crear cuenta");
        btnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaActionPerformed(evt);
            }
        });

        txtContrasenaLogin.setBackground(new java.awt.Color(255, 255, 255));
        txtContrasenaLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtContrasenaLogin.setForeground(new java.awt.Color(0, 0, 0));
        txtContrasenaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContrasenaLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout izquierdoLayout = new javax.swing.GroupLayout(izquierdo);
        izquierdo.setLayout(izquierdoLayout);
        izquierdoLayout.setHorizontalGroup(
            izquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, izquierdoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(90, 90, 90))
            .addGroup(izquierdoLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(izquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtContrasenaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtCorreoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(izquierdoLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel4))
                    .addGroup(izquierdoLayout.createSequentialGroup()
                        .addComponent(btnInciarSesion)
                        .addGap(59, 59, 59)
                        .addComponent(btnCrearCuenta)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        izquierdoLayout.setVerticalGroup(
            izquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(izquierdoLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContrasenaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addGap(13, 13, 13)
                .addGroup(izquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jPanel1.add(izquierdo);
        izquierdo.setBounds(400, 0, 400, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        // TODO add your handling code here:
        RegistroUsuarios registroForm = new RegistroUsuarios();
        registroForm.setVisible(true);
        registroForm.pack();
        registroForm.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    private void btnInciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInciarSesionActionPerformed
        // TODO add your handling code here:
        // Obtenemos el correo y la contraseña ingresados por el usuario
        String correo = txtCorreoLogin.getText().trim();
        String contrasena = new String(txtContrasenaLogin.getPassword());

        // Verificamos si los campos están vacíos
        if (correo.isEmpty() || contrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Hay uno o varios campos vacíos", "Campo obligatorio", JOptionPane.ERROR_MESSAGE);
            return; // Salimos del método si hay campos vacíos
        }

        // Consultamos la base de datos para verificar la autenticación del usuario
        java.sql.Connection conectarbd = null;
        String url = "jdbc:mysql://localhost:3306/gestionusuarios";
        String username = "root";
        String password = "Chris#2006";
        String strSentenciaSelect = "SELECT correo, contrasena FROM usuarios WHERE correo = ? AND contrasena = ?";

        try {
            conectarbd = DriverManager.getConnection(url, username, password);
            PreparedStatement stmt = conectarbd.prepareStatement(strSentenciaSelect);
            stmt.setString(1, correo);
            stmt.setString(2, contrasena);
            ResultSet rs = stmt.executeQuery();

            // Si la consulta devuelve al menos una fila, el usuario es autenticado correctamente
            if (rs.next()) {
                GestionarUsuarios gestionForm = new GestionarUsuarios();
                gestionForm.setVisible(true);
                gestionForm.pack();
                gestionForm.setLocationRelativeTo(null);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Correo o contraseña incorrecta", "Error de credenciales", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al autenticar usuario", "Error de autenticación", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnInciarSesionActionPerformed

    public usuariosBL recuperarDatosGUI() {

        usuariosBL oUsuario = new usuariosBL();
        oUsuario.setCorreo(txtCorreoLogin.getText());

        String contrasena = txtContrasenaLogin.getText();
        oUsuario.setContrasena(contrasena);

        return oUsuario;

    }


    private void txtCorreoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoLoginActionPerformed

    }//GEN-LAST:event_txtCorreoLoginActionPerformed

    private void txtContrasenaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContrasenaLoginActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JButton btnInciarSesion;
    private javax.swing.JPanel derecho;
    private javax.swing.JPanel izquierdo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtContrasenaLogin;
    private javax.swing.JTextField txtCorreoLogin;
    // End of variables declaration//GEN-END:variables
}
